export const products = [
    {
        id: 1,
        srcImage: require('~/asset/img/product/p1.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Artsy',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: true,
        numberSeller: 23,
    },
    {
        id: 2,
        srcImage: require('~/asset/img/product/p2.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Chic',
        price: '$63.85',
        label: '',
        isBestSeller: true,
        isNew: true,
        numberSeller: 108,
    },
    {
        id: 3,
        srcImage: require('~/asset/img/product/p3.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Casual',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: true,
        numberSeller: 26,
    },
    {
        id: 4,
        srcImage: require('~/asset/img/product/p4.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: 'sale',
        isBestSeller: true,
        isNew: true,
        numberSeller: 88,
    },
    {
        id: 5,
        srcImage: require('~/asset/img/product/p5.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Vintage',
        price: '$63.85',
        label: 'hot',
        isBestSeller: true,
        isNew: true,
        numberSeller: 388,
    },
    {
        id: 6,
        srcImage: require('~/asset/img/product/p6.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Jacket',
        price: '$63.85',
        label: 'sale',
        isBestSeller: true,
        isNew: true,
        numberSeller: 66,
    },
    {
        id: 7,
        srcImage: require('~/asset/img/product/p7.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: true,
        numberSeller: 50,
    },
    {
        id: 8,
        srcImage: require('~/asset/img/product/p8.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: true,
        numberSeller: 42,
    },
];
