export const products = [
    {
        id: 1,
        srcImage: require('~/asset/img/product/p1.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Artsy',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: true,
        numberSeller: 23,
        styId: 1,
    },
    {
        id: 2,
        srcImage: require('~/asset/img/product/p2.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Chic',
        price: '$63.85',
        label: '',
        isBestSeller: true,
        isNew: true,
        numberSeller: 108,
        styId: 2,
    },
    {
        id: 3,
        srcImage: require('~/asset/img/product/p3.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Casual',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: true,
        numberSeller: 26,
        styId: 3,
    },
    {
        id: 4,
        srcImage: require('~/asset/img/product/p4.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: 'sale',
        isBestSeller: true,
        isNew: true,
        numberSeller: 88,
        styId: 1,
    },
    {
        id: 5,
        srcImage: require('~/asset/img/product/p5.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Vintage',
        price: '$63.85',
        label: 'hot',
        isBestSeller: true,
        isNew: true,
        numberSeller: 388,
        styId: 2,
    },
    {
        id: 6,
        srcImage: require('~/asset/img/product/p6.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Jacket',
        price: '$63.85',
        label: 'sale',
        isBestSeller: true,
        isNew: true,
        numberSeller: 66,
        styId: 3,
    },
    {
        id: 7,
        srcImage: require('~/asset/img/product/p7.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: true,
        numberSeller: 50,
        styId: 1,
    },
    {
        id: 8,
        srcImage: require('~/asset/img/product/p8.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: true,
        numberSeller: 42,
        styId: 2,
    },
    // add test
    {
        id: 9,
        srcImage: require('~/asset/img/product/p8.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 42,
        styId: 2,
    },
    {
        id: 10,
        srcImage: require('~/asset/img/product/p8.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 42,
        styId: 2,
    },
    {
        id: 11,
        srcImage: require('~/asset/img/product/p8.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 42,
        styId: 2,
    },
    {
        id: 12,
        srcImage: require('~/asset/img/product/p8.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 42,
        styId: 2,
    },

    // page 2
    {
        id: 13,
        srcImage: require('~/asset/img/product/p7.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 50,
        styId: 1,
    },
    {
        id: 14,
        srcImage: require('~/asset/img/product/p7.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 50,
        styId: 1,
    },
    {
        id: 15,
        srcImage: require('~/asset/img/product/p7.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 50,
        styId: 1,
    },
    {
        id: 16,
        srcImage: require('~/asset/img/product/p7.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 50,
        styId: 1,
    },
    {
        id: 17,
        srcImage: require('~/asset/img/product/p7.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 50,
        styId: 1,
    },
    {
        id: 18,
        srcImage: require('~/asset/img/product/p7.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Dress',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 50,
        styId: 1,
    },
    {
        id: 19,
        srcImage: require('~/asset/img/product/p5.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Vintage',
        price: '$63.85',
        label: 'hot',
        isBestSeller: false,
        isNew: false,
        numberSeller: 388,
        styId: 2,
    },
    {
        id: 20,
        srcImage: require('~/asset/img/product/p5.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Vintage',
        price: '$63.85',
        label: 'hot',
        isBestSeller: false,
        isNew: false,
        numberSeller: 388,
        styId: 2,
    },
    {
        id: 21,
        srcImage: require('~/asset/img/product/p5.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Vintage',
        price: '$63.85',
        label: 'hot',
        isBestSeller: false,
        isNew: false,
        numberSeller: 388,
        styId: 2,
    },
    {
        id: 22,
        srcImage: require('~/asset/img/product/p5.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Vintage',
        price: '$63.85',
        label: 'hot',
        isBestSeller: false,
        isNew: false,
        numberSeller: 388,
        styId: 2,
    },
    {
        id: 23,
        srcImage: require('~/asset/img/product/p5.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Vintage',
        price: '$63.85',
        label: 'hot',
        isBestSeller: false,
        isNew: false,
        numberSeller: 388,
        styId: 2,
    },
    {
        id: 24,
        srcImage: require('~/asset/img/product/p5.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Vintage',
        price: '$63.85',
        label: 'hot',
        isBestSeller: false,
        isNew: false,
        numberSeller: 388,
        styId: 2,
    },
    // page 3
    {
        id: 25,
        srcImage: require('~/asset/img/product/p2.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Chic',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 108,
        styId: 2,
    },
    {
        id: 26,
        srcImage: require('~/asset/img/product/p2.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Chic',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 108,
        styId: 2,
    },
    {
        id: 27,
        srcImage: require('~/asset/img/product/p2.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Chic',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 108,
        styId: 2,
    },
    {
        id: 28,
        srcImage: require('~/asset/img/product/p2.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Chic',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 108,
        styId: 2,
    },
    {
        id: 29,
        srcImage: require('~/asset/img/product/p2.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Chic',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 108,
        styId: 2,
    },
    {
        id: 30,
        srcImage: require('~/asset/img/product/p2.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Chic',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 108,
        styId: 2,
    },
    {
        id: 31,
        srcImage: require('~/asset/img/product/p3.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Casual',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 26,
        styId: 3,
    },
    {
        id: 32,
        srcImage: require('~/asset/img/product/p3.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Casual',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 26,
        styId: 3,
    },
    {
        id: 33,
        srcImage: require('~/asset/img/product/p3.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Casual',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 26,
        styId: 3,
    },
    {
        id: 34,
        srcImage: require('~/asset/img/product/p3.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Casual',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 26,
        styId: 3,
    },
    {
        id: 35,
        srcImage: require('~/asset/img/product/p3.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Casual',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 26,
        styId: 3,
    },
    {
        id: 36,
        srcImage: require('~/asset/img/product/p3.png'),
        title: 'Adicolor Classics Joggers',
        categoryName: 'Casual',
        price: '$63.85',
        label: '',
        isBestSeller: false,
        isNew: false,
        numberSeller: 26,
        styId: 3,
    },
];
